### ISSUE TITLE
CPU tmux not working

### ISSUE THREAD

**Issue by arnoldfrancisca** [cyproterone/tmux#1]
Hi, I stumbled opon your config files for tmux trough reddit! I installed everything but for some reason the CPU percentage doesn't work. I have no idea why it ain't working..
![Schermafbeelding 2021-01-22 om 16 37 55](https://user-images.githubusercontent.com/47351180/105511445-2e9e2080-5cd0-11eb-94c1-604857028f64.jpg)

**Comment by cyproterone** [comment]
did you run `bin/tmux-init`?

It requires some dependencies.

or it could be a bug with https://github.com/tmux-plugins/tmux-cpu

I think I had to submit a patch for them to fix either the `CPU` or `MEM` counter for non English locales

**Comment by arnoldfrancisca** [comment]
Sorry for my very late reply!
I've tried what you've mentioned, but that didn't work..
